Check proxy and create a new one if not found.

diff --git a/occi b/occi
--- a/occi
+++ b/occi
@@ -1,5 +1,19 @@
 #!/bin/bash
 : ${OCCI_ENDPOINT:="https://carach5.ics.muni.cz:11443"}
+: ${VO:=fedcloud.egi.eu}
+
+docker run --volumes-from occi-voms-proxy -it \
+	egifedcloud/fedcloud-userinterface \
+	voms-proxy-info -exists 2> /dev/null
+
+if [ $? -ne 0 ]; then
+    echo "Could not find a valid proxy, creating a new one for VO $VO"
+    docker rm occi-voms-proxy &> /dev/null
+    # create proxy after updating crls
+    docker run -it -v ~/.globus:/root/.globus:ro --name occi-voms-proxy \
+	   egifedcloud/fedcloud-userinterface \
+	   /bin/bash -c "(fetch-crl -v -T 30 || true) && voms-proxy-init --voms $VO --rfc"
+fi
 
 docker run --rm --volumes-from occi-voms-proxy -it \
 	   -v $PWD:/data:rw \
